# https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html
---
- name: update db servers
  hosts: db-servers
  remote_user: root

  tasks:
    - name: install mysql-server
      package:
        name: mysql-server
        state: latest

    - name: Install python MySQL module
      apt:
        name: python3-mysqldb

    - name: create wp db
      mysql_db:
          login_password: 'jrP5(pM4P)8;{v(q'
          name: wp
          state: present
      tags: mysql-prep

    - name: Set MySQL root Password
      mysql_user:
        login_host: 'localhost'
        login_user: 'root'
        login_password: 'jrP5(pM4P)8;{v(q'
        name: 'root'
        password: 'jrP5(pM4P)8;{v(q'
        state: present
