# https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html
---
- name: update lb-server
  hosts: lb-servers
  remote_user: root

  tasks:

    - name: install haproxy latest version
      package:
        name: haproxy
        state: latest

    - name: dhparam.pem config file
      copy:
        src: "files/haproxy"
        dest: "/etc/haproxy/haproxy.cfg"

    - name: restart haproxy
      service: name=haproxy state=restarted
