# https://docs.ansible.com/ansible/latest/user_guide/playbooks_intro.html
---
- name: update web servers
  hosts: web-servers
  remote_user: root

  tasks:
    - name: install nginx latest version
      package:
        name: nginx
        state: latest

    - name: write the apache config file
      copy:
        src: test.txt
        dest: /tmp/test.txt

    - name: Add the user 'bog' a primary group of 'sudo'
      user:
        name: bog
        group: sudo

    - name: Install php
      apt:
        name: "{{ item }}"
        state: present
      loop:
            - php-curl
            - php-gd
            - php-intl
            - php-mbstring
            - php-soap
            - php-xml
            - php-xmlrpc
            - php-zip
            - php-fpm
            - php-mysql

    - name: Enabled php-fpm
      systemd:
         name: php7.4-fpm
         enabled: yes

    - name: Create tmp dir
      file:
        path: /home/vagrant/tmp
        state: directory
        owner: root
        group: root
        mode: '666'

    - name: Download wp dist
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /home/vagrant/tmp/lastest.tar.gz

    - name: Unarchive wp
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www/html/
        remote_src: yes
        mode: '775'
        owner: www-data
        group: www-data

    - name: Update nginx config files
      template:
        src: "files/nginx_bmykolaichenko_site"
        dest: "/etc/nginx/sites-available/default"

    - name: link nginx config
      file:
        src: "/etc/nginx/sites-available/default"
        dest: "/etc/nginx/sites-enabled/default"
        state: link

    - name: write the info_php config file
      copy:
        src: info.php
        dest: /var/www/html/info.php

    - name: wp-config
      copy:
        src: wp-config.php
        dest: /var/www/html/wordpress/wp-config.php
      tags: wp-config

    #TODO: enable in future
    - name: install certbot
      package:
        name: certbot
        state: absent

    #TODO: enable in future
    - name: install python3-certbot-nginx latest version
      package:
        name: python3-certbot-nginx
        state: absent

#    - name: run certbot
#      shell: certbot -n --nginx --agree-tos -m 'bmykolaichenko@gmail.com' -d bmykolaichenko.site -d www.bmykolaichenko.site
#      args:
#        executable: /bin/bash

    - name: dhparam.pem config file
      copy:
        src: "certificate/dhparam.pem"
        dest: "/etc/nginx/dhparam.pem"

    - name: self-signed.conf config file
      copy:
        src: "certificate/self-signed.conf"
        dest: "/etc/nginx/snippets/self-signed.conf"

    - name: ssl-params.conf config file
      copy:
        src: "certificate/ssl-params.conf"
        dest: "/etc/nginx/snippets/ssl-params.conf"

    - name: nginx-selfsigned.key config file
      copy:
        src: "certificate/nginx-selfsigned.key"
        dest: "/etc/ssl/private/nginx-selfsigned.key"

    - name: nginx-selfsigned.crt config file
      copy:
        src: "certificate/nginx-selfsigned.crt"
        dest: "/etc/ssl/certs/nginx-selfsigned.crt"

    - name: restart nginx
      service: name=nginx state=restarted
